### ISSUE TITLE
Newline issues

### ISSUE THREAD

**Issue by gabrielbauman** [thymeleaf/thymeleaf-extras-conditionalcomments#1]
While parsing of conditional comments works well using this module, it seems to "eat" the newline immediately before each conditional comment tag and add it immediately after.

So, this:

``` html
<link rel="stylesheet" th:href="@{/assets/css/styles.css}" />
<!--[if lt IE 9]><script th:src="@{/assets/js/html5shiv.js}"></script><![endif]-->
</head>
```

becomes this:

``` html
<link rel="stylesheet" href="/assets/css/styles.css" /><!--[if lt IE 9]><script src="/assets/js/html5shiv.js"></script><![endif]-->

</head>
```

It looks like a newline is added after the comment as well.

Not sure if this affects IE's parsing of conditional comments, but it's certainly a style issue.

**Comment by gabrielbauman** [comment]
Actually, this seems to happen after any comment at all. Looks to be an issue with ThymeLeaf's comment writing, not this module.

**Comment by danielfernandez** [comment]
For the sake of documentation: this is linked to https://github.com/thymeleaf/thymeleaf/issues/151
