### ISSUE TITLE
Thymeleaf 3

### ISSUE THREAD

**Issue by dtrunk90** [thymeleaf/thymeleaf-extras-conditionalcomments#5]
I'm a bit confused about this: https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/standard/processor/StandardConditionalCommentProcessor.java

Is this dialect still needed in Thymeleaf 3?

**Comment by danielfernandez** [comment]
What you point to is not a dialect, it is a processor included in the Standard Dialect since v3.

Processing of IE conditional comments is made by the Thymeleaf core (specifically, the Standard Dialect) since v3. An additional dialect is no longer needed.
