### ISSUE TITLE
Not Compatible with Attoparser 2.0.0.BETA2+

### ISSUE THREAD

**Issue by tribelo** [thymeleaf/thymeleaf-extras-conditionalcomments#6]
Hi There,

We are using thymeleaf-testing which requires attoparser 2.0.0.BETA2+.  We are also using the condtionalcomments library which is not compatible with this version of attoparser.

Can you update conditionalcomments to be compatible with attoparser  2.0.0.BETA2+.

Thanks

**Comment by danielfernandez** [comment]
Actually, the current `2.1.2-SNAPSHOT` version of thymeleaf-extras-conditionalcomments is adapted to AttoParser 2.0, but the stable release (`2.1.1.RELEASE`) is not, yet.

A version `2.1.2.RELEASE` of this dialect will be soon released, which will be presumably the last one (this dialect is not needed anymore as a separate entity in Thymeleaf 3.0)

**Comment by danielfernandez** [comment]
Please note that `thymeleaf-extras-conditionalcomments:2.1.2.RELEASE` has just been released, based on AttoParser 2.0.
